package flow;

import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;

import com.avaya.sce.runtimecommon.IVariableField;
import com.cqgas.tools.util.AppUtil;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2016年8月30日 上午07时11分55秒
 */
public class NoticeInfoQry extends com.avaya.sce.runtime.BasicServlet {
	private static final Logger logs = Logger.getLogger(NoticeInfoQry.class);
	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2016年8月30日 上午07时11分55秒
	 */
	public NoticeInfoQry() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Voice Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2016年8月30日 上午07时11分55秒
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!
		IVariableField noticeMsgField = mySession.getVariableField(IProjectVariables.CQVALUE, IProjectVariables.CQVALUE_FIELD_NOTICEMSG);
		//noticeMsgField.setValue("停气通知 通知如下：因为管道保养，从8月6日 23点起至8月8日23点，天子路停止燃气供应，请附近居民做好相关应急准备，由此给您带来的不便，敬请谅解！");
		IVariableField keyValue = mySession.getVariableField(IProjectVariables.NOTICE_MENU, IProjectVariables.NOTICE_MENU_FIELD_UTTERANCE);
	
		StringBuffer sb  = new StringBuffer("");
		if("1".equals(keyValue.getStringValue())){
			//停气通知

			try {
				List list = AppUtil.getStopGasNotice();
				for(int i=0;i<list.size();i++){
					String content = ((java.util.Map)(list.get(i))).get("bulcontent").toString();
					sb.append(content);
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}else if("2".equals(keyValue.getStringValue())){
			try {
				List list = AppUtil.getImportantNotice();
				for(int i=0;i<list.size();i++){
					String content = ((java.util.Map)(list.get(i))).get("bulcontent").toString();
					sb.append(content);
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		logs.debug("停气通知："+sb.toString());
		noticeMsgField.setValue(sb.toString());
	
	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("checkNotice", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
