package English.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2016年8月29日 下午08时19分59秒
 */
public class CollectYearMonth extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for CollectYearMonth.
    */
    public CollectYearMonth() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("digits");
        setOptions("bWlubGVuZ3RoPTY7bWF4bGVuZ3RoPTc=");
		//}}END:CLASS:CONSTRUCTOR
    }

}

