package English.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2016年9月9日 下午02时04分10秒
 */
public class CollectAnyOneKey extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for CollectAnyOneKey.
    */
    public CollectAnyOneKey() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("CollectAnyOneKey.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

