package Chinese.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2016年8月29日 上午11时18分31秒
 */
public class CollectCustNum extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for CollectCustNum.
    */
    public CollectCustNum() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("zh-cn");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("digits");
        setOptions("minlength=5;maxlength=20");
		//}}END:CLASS:CONSTRUCTOR
    }

}

