package Chinese.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2016年8月29日 下午08时19分59秒
 */
public class CollectYearMonth extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for CollectYearMonth.
    */
    public CollectYearMonth() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("zh-cn");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("number");
        setOptions("");
		//}}END:CLASS:CONSTRUCTOR
    }

}

